SOURCES         = \
                  caloriestracker/ui/canvaschart.py \
                  caloriestracker/ui/Ui_frmAbout.py \
                  caloriestracker/ui/frmAbout.py \
                  caloriestracker/ui/Ui_frmAccess.py \
                  caloriestracker/ui/frmAccess.py \
                  caloriestracker/ui/Ui_frmCompaniesAdd.py \
                  caloriestracker/ui/frmCompaniesAdd.py \
                  caloriestracker/ui/Ui_frmInit.py \
                  caloriestracker/ui/frmInit.py \
                  caloriestracker/ui/Ui_frmBiometricsAdd.py \
                  caloriestracker/ui/frmBiometricsAdd.py \
                  caloriestracker/ui/Ui_frmProductsAdd.py \
                  caloriestracker/ui/frmProductsAdd.py \
                  caloriestracker/ui/Ui_frmProductsElaboratedAdd.py \
                  caloriestracker/ui/frmProductsElaboratedAdd.py \
                  caloriestracker/ui/Ui_frmProductsInElaboratedProductAdd.py \
                  caloriestracker/ui/frmProductsInElaboratedProductAdd.py \
                  caloriestracker/ui/Ui_frmHelp.py \
                  caloriestracker/ui/frmHelp.py \
                  caloriestracker/ui/Ui_frmMain.py \
                  caloriestracker/ui/frmMain.py \
                  caloriestracker/ui/Ui_frmMealsAdd.py \
                  caloriestracker/ui/frmMealsAdd.py \
                  caloriestracker/ui/Ui_frmSettings.py \
                  caloriestracker/ui/frmSettings.py \
                  caloriestracker/ui/myqlineedit.py \
                  caloriestracker/ui/myqtablewidget.py \
                  caloriestracker/ui/Ui_wdgBiometrics.py \
                  caloriestracker/ui/wdgBiometrics.py \
                  caloriestracker/ui/Ui_wdgCuriosities.py \
                  caloriestracker/ui/wdgCuriosities.py \
                  caloriestracker/ui/Ui_wdgCuriosity.py \
                  caloriestracker/ui/wdgCuriosity.py \
                  caloriestracker/ui/Ui_wdgDatetime.py \
                  caloriestracker/ui/wdgDatetime.py \
                  caloriestracker/ui/Ui_wdgMeals.py \
                  caloriestracker/ui/wdgMeals.py \
                  caloriestracker/ui/Ui_wdgProducts.py \
                  caloriestracker/ui/wdgProducts.py \
                  caloriestracker/ui/Ui_wdgProductsElaborated.py \
                  caloriestracker/ui/wdgProductsElaborated.py \
                  caloriestracker/ui/Ui_wdgProductsDataMove.py \
                  caloriestracker/ui/wdgProductsDataMove.py \
                  caloriestracker/ui/Ui_wdgYear.py \
                  caloriestracker/ui/wdgYear.py \
                  caloriestracker/ui/Ui_wdgYearMonth.py \
                  caloriestracker/ui/wdgYearMonth.py \
                  caloriestracker/caloriestracker.py \
                  caloriestracker/caloriestracker_console.py \
                  caloriestracker/caloriestracker_init.py \
                  caloriestracker/libcaloriestracker.py \
                  caloriestracker/mem.py \
                  caloriestracker/ui/qtablewidgetitems.py \
                  caloriestracker/admin_pg.py \
                  caloriestracker/database_update.py \
                  caloriestracker/translationlanguages.py \
                  caloriestracker/datetime_functions.py \
                  caloriestracker/package_resources.py \
                  caloriestracker/decorators.py \
                  caloriestracker/libcaloriestrackerfunctions.py \
                  caloriestracker/version.py \
                  caloriestracker/connection_pg.py \
                  caloriestracker/github.py \
                  caloriestracker/shortcuts.py \
                  caloriestracker/connection_pg_qt.py \
                  caloriestracker/hardcoded_strings.py \
                  caloriestracker/libcaloriestrackertypes.py \
                  caloriestracker/contribution.py \
                  caloriestracker/libmanagers.py \
                  caloriestracker/text_inputs.py

FORMS           = \
                  caloriestracker/ui/frmAbout.ui \
                  caloriestracker/ui/frmAccess.ui \
                  caloriestracker/ui/frmBiometricsAdd.ui \
                  caloriestracker/ui/frmCompaniesAdd.ui \
                  caloriestracker/ui/frmHelp.ui \
                  caloriestracker/ui/frmMain.ui \
                  caloriestracker/ui/frmMealsAdd.ui \
                  caloriestracker/ui/frmSettings.ui \
                  caloriestracker/ui/frmProductsAdd.ui \
                  caloriestracker/ui/frmProductsElaboratedAdd.ui \
                  caloriestracker/ui/frmProductsInElaboratedProductAdd.ui \
                  caloriestracker/ui/wdgBiometrics.ui \
                  caloriestracker/ui/wdgDatetime.ui \
                  caloriestracker/ui/wdgMeals.ui \
                  caloriestracker/ui/wdgProducts.ui \
                  caloriestracker/ui/wdgProductsElaborated.ui \
                  caloriestracker/ui/wdgProductsDataMove.ui \
                  caloriestracker/ui/wdgYear.ui \
                  caloriestracker/ui/wdgYearMonth.ui

TRANSLATIONS    = caloriestracker/i18n/caloriestracker_es.ts \
                  caloriestracker/i18n/caloriestracker_fr.ts \
                  caloriestracker/i18n/caloriestracker_ru.ts \
                  caloriestracker/i18n/caloriestracker_ro.ts \
                  caloriestracker/i18n/caloriestracker_en.ts

