# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'caloriestracker/ui/frmMealsAdd.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmMealsAdd(object):
    def setupUi(self, frmMealsAdd):
        frmMealsAdd.setObjectName("frmMealsAdd")
        frmMealsAdd.setWindowModality(QtCore.Qt.WindowModal)
        frmMealsAdd.resize(692, 366)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/caloriestracker/meals.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmMealsAdd.setWindowIcon(icon)
        frmMealsAdd.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(frmMealsAdd)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl = QtWidgets.QLabel(frmMealsAdd)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl.setFont(font)
        self.lbl.setStyleSheet("color: rgb(0, 128, 0);")
        self.lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl.setObjectName("lbl")
        self.verticalLayout.addWidget(self.lbl)
        self.wdgDT = wdgDatetime(frmMealsAdd)
        self.wdgDT.setObjectName("wdgDT")
        self.verticalLayout.addWidget(self.wdgDT)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(frmMealsAdd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.cmbProducts = QtWidgets.QComboBox(frmMealsAdd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbProducts.sizePolicy().hasHeightForWidth())
        self.cmbProducts.setSizePolicy(sizePolicy)
        self.cmbProducts.setEditable(True)
        self.cmbProducts.setObjectName("cmbProducts")
        self.horizontalLayout_3.addWidget(self.cmbProducts)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(frmMealsAdd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.cmbFormats = QtWidgets.QComboBox(frmMealsAdd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFormats.sizePolicy().hasHeightForWidth())
        self.cmbFormats.setSizePolicy(sizePolicy)
        self.cmbFormats.setEditable(False)
        self.cmbFormats.setObjectName("cmbFormats")
        self.horizontalLayout_4.addWidget(self.cmbFormats)
        self.cmbMult = QtWidgets.QComboBox(frmMealsAdd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMult.sizePolicy().hasHeightForWidth())
        self.cmbMult.setSizePolicy(sizePolicy)
        self.cmbMult.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.cmbMult.setObjectName("cmbMult")
        self.horizontalLayout_4.addWidget(self.cmbMult)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(frmMealsAdd)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.spnAmount = myQDoubleSpinBox(frmMealsAdd)
        self.spnAmount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spnAmount.setMaximum(1000000.0)
        self.spnAmount.setProperty("value", 100.0)
        self.spnAmount.setObjectName("spnAmount")
        self.horizontalLayout.addWidget(self.spnAmount)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.bb = QtWidgets.QDialogButtonBox(frmMealsAdd)
        self.bb.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.bb.setObjectName("bb")
        self.verticalLayout.addWidget(self.bb)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(frmMealsAdd)
        QtCore.QMetaObject.connectSlotsByName(frmMealsAdd)
        frmMealsAdd.setTabOrder(self.cmbProducts, self.spnAmount)

    def retranslateUi(self, frmMealsAdd):
        _translate = QtCore.QCoreApplication.translate
        frmMealsAdd.setWindowTitle(_translate("frmMealsAdd", "Managing meals"))
        self.label_2.setText(_translate("frmMealsAdd", "Select a product"))
        self.label_4.setText(_translate("frmMealsAdd", "Select a format"))
        self.label_3.setText(_translate("frmMealsAdd", "Add an amount"))
        self.spnAmount.setSuffix(_translate("frmMealsAdd", " g"))
from caloriestracker.ui.myqdoublespinbox import myQDoubleSpinBox
from caloriestracker.ui.wdgDatetime import wdgDatetime
import caloriestracker.images.caloriestracker_rc
