# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'caloriestracker/ui/wdgProductsElaborated.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wdgProductsElaborated(object):
    def setupUi(self, wdgProductsElaborated):
        wdgProductsElaborated.setObjectName("wdgProductsElaborated")
        wdgProductsElaborated.resize(892, 654)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(wdgProductsElaborated)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl = QtWidgets.QLabel(wdgProductsElaborated)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl.setFont(font)
        self.lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl.setObjectName("lbl")
        self.verticalLayout_3.addWidget(self.lbl)
        self.groupBox = QtWidgets.QGroupBox(wdgProductsElaborated)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.txt = QtWidgets.QLineEdit(self.groupBox)
        self.txt.setObjectName("txt")
        self.horizontalLayout.addWidget(self.txt)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.cmd = QtWidgets.QToolButton(self.groupBox)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/caloriestracker/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cmd.setIcon(icon)
        self.cmd.setObjectName("cmd")
        self.horizontalLayout_3.addWidget(self.cmd)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setEnabled(False)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.tblProductsElaborated = myQTableWidget(wdgProductsElaborated)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblProductsElaborated.sizePolicy().hasHeightForWidth())
        self.tblProductsElaborated.setSizePolicy(sizePolicy)
        self.tblProductsElaborated.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tblProductsElaborated.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblProductsElaborated.setAlternatingRowColors(True)
        self.tblProductsElaborated.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblProductsElaborated.setObjectName("tblProductsElaborated")
        self.tblProductsElaborated.setColumnCount(0)
        self.tblProductsElaborated.setRowCount(0)
        self.tblProductsElaborated.horizontalHeader().setStretchLastSection(False)
        self.tblProductsElaborated.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tblProductsElaborated)
        self.lblFound = QtWidgets.QLabel(wdgProductsElaborated)
        self.lblFound.setObjectName("lblFound")
        self.verticalLayout_3.addWidget(self.lblFound)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.actionProductNew = QtWidgets.QAction(wdgProductsElaborated)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/caloriestracker/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProductNew.setIcon(icon1)
        self.actionProductNew.setObjectName("actionProductNew")
        self.actionProductDelete = QtWidgets.QAction(wdgProductsElaborated)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/caloriestracker/list-remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProductDelete.setIcon(icon2)
        self.actionProductDelete.setObjectName("actionProductDelete")
        self.actionProductEdit = QtWidgets.QAction(wdgProductsElaborated)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/caloriestracker/document-edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProductEdit.setIcon(icon3)
        self.actionProductEdit.setObjectName("actionProductEdit")

        self.retranslateUi(wdgProductsElaborated)
        QtCore.QMetaObject.connectSlotsByName(wdgProductsElaborated)
        wdgProductsElaborated.setTabOrder(self.txt, self.tblProductsElaborated)

    def retranslateUi(self, wdgProductsElaborated):
        _translate = QtCore.QCoreApplication.translate
        self.lbl.setText(_translate("wdgProductsElaborated", "Elaborated products list"))
        self.groupBox.setTitle(_translate("wdgProductsElaborated", "Select your search"))
        self.label.setText(_translate("wdgProductsElaborated", "Enter a string"))
        self.lblFound.setText(_translate("wdgProductsElaborated", "Registers found"))
        self.actionProductNew.setText(_translate("wdgProductsElaborated", "New product"))
        self.actionProductNew.setToolTip(_translate("wdgProductsElaborated", "New user product"))
        self.actionProductDelete.setText(_translate("wdgProductsElaborated", "Delete product"))
        self.actionProductDelete.setToolTip(_translate("wdgProductsElaborated", "Delete user product"))
        self.actionProductEdit.setText(_translate("wdgProductsElaborated", "Edit product"))
        self.actionProductEdit.setToolTip(_translate("wdgProductsElaborated", "Edit product"))
from caloriestracker.ui.myqtablewidget import myQTableWidget
import caloriestracker.images.caloriestracker_rc
