ALTER TABLE meals RENAME COLUMN user_id TO users_id;
ALTER TABLE products ADD COLUMN cholesterol NUMERIC(10,2) DEFAULT 0;
ALTER TABLE products ADD COLUMN sodiumm NUMERIC(10,2) DEFAULT 0;
ALTER TABLE products ADD COLUMN potassium NUMERIC(10,2) DEFAULT 0;
ALTER TABLE products ADD COLUMN fiber NUMERIC(10,2) DEFAULT 0;
ALTER TABLE products ADD COLUMN sugars NUMERIC(10,2) DEFAULT 0;
ALTER TABLE products ADD COLUMN saturated_fat NUMERIC(10,2) DEFAULT 0;
