from PyQt5.QtCore import QT_TRANSLATE_NOOP
QT_TRANSLATE_NOOP('HardcodedStrings','Aceite de girasol')
QT_TRANSLATE_NOOP('HardcodedStrings','Aceite de oliva virgen extra')
QT_TRANSLATE_NOOP('HardcodedStrings','Agua')
QT_TRANSLATE_NOOP('HardcodedStrings','Ajo')
QT_TRANSLATE_NOOP('HardcodedStrings','Arándanos')
QT_TRANSLATE_NOOP('HardcodedStrings','Arroz crudo')
QT_TRANSLATE_NOOP('HardcodedStrings','Azúcar')
QT_TRANSLATE_NOOP('HardcodedStrings','Banana')
QT_TRANSLATE_NOOP('HardcodedStrings','Bread')
QT_TRANSLATE_NOOP('HardcodedStrings','Cacahuetes fritos')
QT_TRANSLATE_NOOP('HardcodedStrings','Castañas')
QT_TRANSLATE_NOOP('HardcodedStrings','Cebolla')
QT_TRANSLATE_NOOP('HardcodedStrings','Cerveza sin alcohol')
QT_TRANSLATE_NOOP('HardcodedStrings','Chirimoya')
QT_TRANSLATE_NOOP('HardcodedStrings','Cola Cao Original')
QT_TRANSLATE_NOOP('HardcodedStrings','Cordero asado')
QT_TRANSLATE_NOOP('HardcodedStrings','Costillas de cerdo')
QT_TRANSLATE_NOOP('HardcodedStrings','Croquetas de jamón')
QT_TRANSLATE_NOOP('HardcodedStrings','Espárragos trigueros')
QT_TRANSLATE_NOOP('HardcodedStrings','Gambas')
QT_TRANSLATE_NOOP('HardcodedStrings','Helado')
QT_TRANSLATE_NOOP('HardcodedStrings','Huevo duro')
QT_TRANSLATE_NOOP('HardcodedStrings','Huevos')
QT_TRANSLATE_NOOP('HardcodedStrings','Huevos fritos')
QT_TRANSLATE_NOOP('HardcodedStrings','Jamón serrano')
QT_TRANSLATE_NOOP('HardcodedStrings','Kiwi')
QT_TRANSLATE_NOOP('HardcodedStrings','Lambrusco')
QT_TRANSLATE_NOOP('HardcodedStrings','Leche condensada desnatada. Nutricia')
QT_TRANSLATE_NOOP('HardcodedStrings','Leche entera')
QT_TRANSLATE_NOOP('HardcodedStrings','Leche evaporada')
QT_TRANSLATE_NOOP('HardcodedStrings','Lentejas')
QT_TRANSLATE_NOOP('HardcodedStrings','Mango')
QT_TRANSLATE_NOOP('HardcodedStrings','Mantequilla')
QT_TRANSLATE_NOOP('HardcodedStrings','Manzana')
QT_TRANSLATE_NOOP('HardcodedStrings','Mayonesa')
QT_TRANSLATE_NOOP('HardcodedStrings','Mermelada')
QT_TRANSLATE_NOOP('HardcodedStrings','Mermelada de fresa')
QT_TRANSLATE_NOOP('HardcodedStrings','Miel')
QT_TRANSLATE_NOOP('HardcodedStrings','Mousse de foie de pato')
QT_TRANSLATE_NOOP('HardcodedStrings','Nectarina')
QT_TRANSLATE_NOOP('HardcodedStrings','Palmera de chocolate')
QT_TRANSLATE_NOOP('HardcodedStrings','Pan blanco')
QT_TRANSLATE_NOOP('HardcodedStrings','Pan de molde')
QT_TRANSLATE_NOOP('HardcodedStrings','Paraguaya')
QT_TRANSLATE_NOOP('HardcodedStrings','Patata cruda')
QT_TRANSLATE_NOOP('HardcodedStrings','Patatas fritas')
QT_TRANSLATE_NOOP('HardcodedStrings','Pera')
QT_TRANSLATE_NOOP('HardcodedStrings','Persimón')
QT_TRANSLATE_NOOP('HardcodedStrings','Picadillo')
QT_TRANSLATE_NOOP('HardcodedStrings','Pimiento verde')
QT_TRANSLATE_NOOP('HardcodedStrings','Pimientos de padrón')
QT_TRANSLATE_NOOP('HardcodedStrings','Pizza genérica de masa gruesa con queso')
QT_TRANSLATE_NOOP('HardcodedStrings','Plátano')
QT_TRANSLATE_NOOP('HardcodedStrings','Puerro')
QT_TRANSLATE_NOOP('HardcodedStrings','Queso de cabra')
QT_TRANSLATE_NOOP('HardcodedStrings','Queso marcarpone')
QT_TRANSLATE_NOOP('HardcodedStrings','Ron')
QT_TRANSLATE_NOOP('HardcodedStrings','Sal')
QT_TRANSLATE_NOOP('HardcodedStrings','Setas')
QT_TRANSLATE_NOOP('HardcodedStrings','Tortilla de patata')
QT_TRANSLATE_NOOP('HardcodedStrings','Uva')
QT_TRANSLATE_NOOP('HardcodedStrings','Zanahoria')
