from PyQt5.QtCore import QT_TRANSLATE_NOOP
QT_TRANSLATE_NOOP('HardcodedStrings','Alcohol-free beer')
QT_TRANSLATE_NOOP('HardcodedStrings','Apple')
QT_TRANSLATE_NOOP('HardcodedStrings','Bacon')
QT_TRANSLATE_NOOP('HardcodedStrings','Banana')
QT_TRANSLATE_NOOP('HardcodedStrings','Blueberries')
QT_TRANSLATE_NOOP('HardcodedStrings','Boiled egg')
QT_TRANSLATE_NOOP('HardcodedStrings','Bread')
QT_TRANSLATE_NOOP('HardcodedStrings','Butter')
QT_TRANSLATE_NOOP('HardcodedStrings','Carrot')
QT_TRANSLATE_NOOP('HardcodedStrings','Cauliflower')
QT_TRANSLATE_NOOP('HardcodedStrings','Cherimoya')
QT_TRANSLATE_NOOP('HardcodedStrings','Chestnuts')
QT_TRANSLATE_NOOP('HardcodedStrings','Chicken. Raw')
QT_TRANSLATE_NOOP('HardcodedStrings','Chips')
QT_TRANSLATE_NOOP('HardcodedStrings','Churros')
QT_TRANSLATE_NOOP('HardcodedStrings','Cola Cao Original')
QT_TRANSLATE_NOOP('HardcodedStrings','Croissant')
QT_TRANSLATE_NOOP('HardcodedStrings','Duck foie grass mousse')
QT_TRANSLATE_NOOP('HardcodedStrings','Eggs')
QT_TRANSLATE_NOOP('HardcodedStrings','Extra virgin olive oil')
QT_TRANSLATE_NOOP('HardcodedStrings','Fried eggs')
QT_TRANSLATE_NOOP('HardcodedStrings','Fried peanuts')
QT_TRANSLATE_NOOP('HardcodedStrings','Garlic')
QT_TRANSLATE_NOOP('HardcodedStrings','Goat cheese')
QT_TRANSLATE_NOOP('HardcodedStrings','Grape')
QT_TRANSLATE_NOOP('HardcodedStrings','Green asparagus')
QT_TRANSLATE_NOOP('HardcodedStrings','Green pepper')
QT_TRANSLATE_NOOP('HardcodedStrings','Ham')
QT_TRANSLATE_NOOP('HardcodedStrings','Ham croquettes')
QT_TRANSLATE_NOOP('HardcodedStrings','Honey')
QT_TRANSLATE_NOOP('HardcodedStrings','Ice cream')
QT_TRANSLATE_NOOP('HardcodedStrings','Jam')
QT_TRANSLATE_NOOP('HardcodedStrings','Kiwi')
QT_TRANSLATE_NOOP('HardcodedStrings','Lambrusco wine')
QT_TRANSLATE_NOOP('HardcodedStrings','Leek')
QT_TRANSLATE_NOOP('HardcodedStrings','Lentils')
QT_TRANSLATE_NOOP('HardcodedStrings','Mango')
QT_TRANSLATE_NOOP('HardcodedStrings','Mascarpone cheese')
QT_TRANSLATE_NOOP('HardcodedStrings','Mayonnaise')
QT_TRANSLATE_NOOP('HardcodedStrings','Menestra de verduras')
QT_TRANSLATE_NOOP('HardcodedStrings','Minced meat')
QT_TRANSLATE_NOOP('HardcodedStrings','Mushrooms (Fungi)')
QT_TRANSLATE_NOOP('HardcodedStrings','Nectarine')
QT_TRANSLATE_NOOP('HardcodedStrings','Onion')
QT_TRANSLATE_NOOP('HardcodedStrings','Palmera de chocolate')
QT_TRANSLATE_NOOP('HardcodedStrings','Panettone')
QT_TRANSLATE_NOOP('HardcodedStrings','Pear')
QT_TRANSLATE_NOOP('HardcodedStrings','Persimmon')
QT_TRANSLATE_NOOP('HardcodedStrings','Pimientos de padrón')
QT_TRANSLATE_NOOP('HardcodedStrings','Plantain')
QT_TRANSLATE_NOOP('HardcodedStrings','Pork ribs')
QT_TRANSLATE_NOOP('HardcodedStrings','Prawns')
QT_TRANSLATE_NOOP('HardcodedStrings','Pumpkin')
QT_TRANSLATE_NOOP('HardcodedStrings','Roast lamb')
QT_TRANSLATE_NOOP('HardcodedStrings','Rum')
QT_TRANSLATE_NOOP('HardcodedStrings','Salt')
QT_TRANSLATE_NOOP('HardcodedStrings','Sandwich loaf')
QT_TRANSLATE_NOOP('HardcodedStrings','Saturn peach')
QT_TRANSLATE_NOOP('HardcodedStrings','Spanish omelette')
QT_TRANSLATE_NOOP('HardcodedStrings','Strawberries')
QT_TRANSLATE_NOOP('HardcodedStrings','Strawberry jam')
QT_TRANSLATE_NOOP('HardcodedStrings','Sugar')
QT_TRANSLATE_NOOP('HardcodedStrings','Sunflower oil')
QT_TRANSLATE_NOOP('HardcodedStrings','Tangerines')
QT_TRANSLATE_NOOP('HardcodedStrings','Thick Crust Pizza with cheese')
QT_TRANSLATE_NOOP('HardcodedStrings','Uncooked patato')
QT_TRANSLATE_NOOP('HardcodedStrings','Uncooked rice')
QT_TRANSLATE_NOOP('HardcodedStrings','Water')
QT_TRANSLATE_NOOP('HardcodedStrings','White bread')
QT_TRANSLATE_NOOP('HardcodedStrings','Whole milk')
QT_TRANSLATE_NOOP('HardcodedStrings','Zucchini')

#Formats
QT_TRANSLATE_NOOP('HardcodedStrings','Bag')
QT_TRANSLATE_NOOP('HardcodedStrings','Bar')
QT_TRANSLATE_NOOP('HardcodedStrings','Big')
QT_TRANSLATE_NOOP('HardcodedStrings','Big can')
QT_TRANSLATE_NOOP('HardcodedStrings','Can')
QT_TRANSLATE_NOOP('HardcodedStrings','Can 33cl')
QT_TRANSLATE_NOOP('HardcodedStrings','Cookie')
QT_TRANSLATE_NOOP('HardcodedStrings','Drained can')
QT_TRANSLATE_NOOP('HardcodedStrings','Drained small can')
QT_TRANSLATE_NOOP('HardcodedStrings','Little bag')
QT_TRANSLATE_NOOP('HardcodedStrings','Little stick')
QT_TRANSLATE_NOOP('HardcodedStrings','Medium')
QT_TRANSLATE_NOOP('HardcodedStrings','Package')
QT_TRANSLATE_NOOP('HardcodedStrings','Pill')
QT_TRANSLATE_NOOP('HardcodedStrings','Slice')
QT_TRANSLATE_NOOP('HardcodedStrings','Toast')
QT_TRANSLATE_NOOP('HardcodedStrings','Tray')
QT_TRANSLATE_NOOP('HardcodedStrings','Unit')
QT_TRANSLATE_NOOP('HardcodedStrings','Vacuum container')

#Foodtypes
QT_TRANSLATE_NOOP('HardcodedStrings','Alcoholic drinks')
QT_TRANSLATE_NOOP('HardcodedStrings','Bread and cereals')
QT_TRANSLATE_NOOP('HardcodedStrings','Dairy products')
QT_TRANSLATE_NOOP('HardcodedStrings','Diet drinks')
QT_TRANSLATE_NOOP('HardcodedStrings','Dry nuts')
QT_TRANSLATE_NOOP('HardcodedStrings','Eggs')
QT_TRANSLATE_NOOP('HardcodedStrings','Fish')
QT_TRANSLATE_NOOP('HardcodedStrings','Fruit')
QT_TRANSLATE_NOOP('HardcodedStrings','Homemade food')
QT_TRANSLATE_NOOP('HardcodedStrings','Legumes')
QT_TRANSLATE_NOOP('HardcodedStrings','Meat')
QT_TRANSLATE_NOOP('HardcodedStrings','Oils and fats')
QT_TRANSLATE_NOOP('HardcodedStrings','Processed foods')
QT_TRANSLATE_NOOP('HardcodedStrings','Soups and infusions')
QT_TRANSLATE_NOOP('HardcodedStrings','Spices')
QT_TRANSLATE_NOOP('HardcodedStrings','Sugary drinks')
QT_TRANSLATE_NOOP('HardcodedStrings','Sweets')
QT_TRANSLATE_NOOP('HardcodedStrings','Vegetables')
QT_TRANSLATE_NOOP('HardcodedStrings','Water')
