select;
update products set name='Sunflower oil' where id=91;
update products set name='Extra virgin olive oil' where id=40;
update products set name='Water' where id=61;
update products set name='Garlic' where id=49;
update products set name='Blueberries' where id=119;
update products set name='Uncooked rice' where id=92;
update products set name='Sugar' where id=120;
update products set name='Banana' where id=35;
update products set name='Fried peanuts' where id=94;
update products set name='Chestnuts' where id=122;
update products set name='Onion' where id=67;
update products set name='Alcohol-free beer' where id=96;
update products set name='Cherimoya' where id=124;
update products set name='Roast lamb' where id=128;
update products set name='Pork ribs' where id=68;
update products set name='Ham croquettes' where id=97;
update products set name='Green asparagus' where id=30;
update products set name='Prawns' where id=10;
update products set name='Ice cream' where id=100;
update products set name='Boiled egg' where id=137;
update products set name='Eggs' where id=11;
update products set name='Fried eggs' where id=101;
update products set name='Ham' where id=103;
update products set name='Lambrusco wine' where id=105;
update products set companies_id=8, system_company=True where id=87;
update products set name='Whole milk' where id=4;
update products set companies_id=1, system_company=True where id=75;
update products set name='Lentils' where id=141;
update products set name='Butter' where id=7;
update products set name='Apple' where id=8;
update products set name='Mayonnaise' where id=106;
update products set name='Jam' where id=6;
update products set name='Strawberry jam' where id=25;
update products set name='Honey' where id=21;
update products set name='Duck foie grass mousse' where id=107;
update products set name='Nectarine' where id=42;
update products set name='White bread' where id=23;
update products set name='Sandwich loaf' where id=48;
update products set name='Saturn peach' where id=2;
update products set name='Uncooked patato' where id=147;
update products set name='Chips' where id=82;
update products set name='Pear' where id=108;
update products set name='Persimmon' where id=150;
update products set name='Minced meat' where id=109;
update products set name='Green pepper' where id=50;
update products set name='Thick Crust Pizza with cheese' where id=89;
update products set name='Plantain' where id=55;
update products set name='Leek' where id=84;
update products set name='Goat cheese' where id=111;
update products set name='Mascarpone cheese' where id=112;
update products set name='Rum' where id=113;
update products set name='Salt' where id=156;
update products set name='Mushrooms (Fungi)' where id=12;
update products set name='Spanish omelette' where id=114;
update products set name='Grape' where id=115;
update products set name='Carrot' where id=86;
